#!/bin/sh
# Copyright (c) 2015, Ricky Gallamore
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.

PORTEST_VERSION="0.0.8"

usage() {
	cat << EOF
Usage: portest [-m git] [-f bulkfile] [-U default2] [-d PORTSDIR] [-abcdprRtTuv] \\
               file.diff file2.diff ...

Parameters:
    -a     --  Do everything except revert and port test (-ptf build.ports.txt)
    -c     --  Create repo, see -m for supported protocols, default is git
    -f     --  Generate a poudiere usable bulk file
    -p     --  Patch, will exit on fail with output
               portsnap will create a backup directory
               which is used on soft reverts (-r) and updates (-u)
    -r     --  Soft Revert, quick and effective
               portsnap uses backup created when patch (-p, -P) is used, fast
               git (-r) is same as (-R) see below
               svn reverts all files from input patchfiles, fast
    -R     --  Hard Revert, portsnap will rebuild tree, very slow
               git does hard reset and cleans all files, fast
               svn removed all files via status and revert -R, very slow!!
    -t     --  Test with portlint
    -T     --  Test with port test, or poudriere depending on
               USE_POUDRIERE
    -u     --  Update repo, git will stash and stash pop on updates
               portsnap do a soft revert if a backup directory exists
    -v     --  Show version of portest then exit
Options:
    -b     --  Generate the list of cat/ports based on port tree
               instead of diff, git and svn only, slow
    -d     --  Sets PORTSDIR, -U overrides this option
    -j     --  Jails used for poudriere, if multiple are used
               must be in "" with a space as a seperator,
               only used with -T option
    -m     --  Repo method, only used with -c valid methods are
               git,git+https,git+ssh,svn,svn+file,svn+http,
               svn+https,svn+ssh,portsnap  default method is git
    -U     --  Sets USE_POUDRIERE="YES" and sets port tree to use

By default, (no options) portest does nothing
EOF
	exit 1
}

ALL="0"
POUDRIERE_BULK="0"
DO_PATCH="0"
REVERT_SOFT="0"
REVERT_HARD="0"
TEST_PORTLINT="0"
TEST_BUILD="0"
REPO_BUILD_LIST="0"
CREATE_REPO="0"
UPDATE_REPO="0"

while getopts ":abcd:j:f:m:prRtTuU:v" FLAG; do
	case "${FLAG}" in
	a)
		ALL="1"
		;;
	b)
		REPO_BUILD_LIST="1"
		;;
	c)
		CREATE_REPO="1"
		;;
	d)
		PORTSDIR="${OPTARG}"
		;;
	j)
		POUDRIERE_JAILS="${OPTARG}"
		;;
	f)
		POUDRIERE_BULK="1"
		POUDRIERE_BULK_FILE="${OPTARG}"
		;;
	m)	
		METHOD="${OPTARG}"
		;;
	p)
		DO_PATCH="1"
		;;
	r)
		REVERT_SOFT="1"
		;;
	R)
		REVERT_HARD="1"
		;;
	t)
		TEST_PORTLINT="1"
		;;
	T)
		TEST_BUILD="1"
		;;
	u)
		UPDATE_REPO="1"
		;;
	U)
		USE_POUDRIERE="YES"
		POUDRIERE_PORT="${OPTARG}"
		;;
	v)
		echo "${PORTEST_VERSION}"
		exit 0
	esac
done

[ $# -lt 1 ] && usage

shift "$((OPTIND-1))"

if [ ${REPO_BUILD_LIST} -ne 1 ]; then
[ $(( ALL + POUDRIERE_BULK + DO_PATCH + REVERT_SOFT + TEST_PORTLINT + TEST_BUILD )) -ge 1 ] && [ $# -lt 1 ] && usage
elif [ $(( DO_PATCH )) -ge 1 ] && [ $# -lt 1 ]; then
	usage;
fi

: ${METHOD:="git"}
if [ "${CREATE_REPO}" -eq "1" ] && [ "${USE_POUDRIERE}" != "YES" ]; then
	: ${GIT_URL:="github.com/freebsd/freebsd-ports"}
	: ${SVN_URL:="svn.FreeBSD.org/ports"}
	case ${METHOD} in
	git) PROTO="git" ;;
	git+https) PROTO="https" ;;
	git+ssh) PROTO="git" ;;
	svn) PROTO="svn" ;;
	svn+file) PROTO="file" ;;
	svn+http) PROTO="http" ;;
	svn+https) PROTO="https" ;;
	svn+ssh) PROTO="svn+ssh" ;;
	portsnap) ;;
	*) usage;;
	esac

	case ${METHOD} in
	git*) : ${BRANCH:="master"};;
	svn*) : ${BRANCH:="head"} ;;
	esac

	case ${METHOD} in
	git+ssh) GIT_REPO_URL="`echo ${PROTO}@${GIT_URL} | sed 's/\//\:&/'`" ;;
	git*) GIT_REPO_URL="${PROTO}://${GIT_URL}" ;;
	svn*) SVN_REPO_URL="${PROTO}://${SVN_URL}/${BRANCH}" ;;
	esac
fi

: ${PATCH:="patch"}
: ${PATCH_SVN_ARGS:="-Esf"}
: ${PATCH_GIT_ARGS:="-Esfp1"}
: ${PATCH_PATCH_ARGS:="-Esf"}
: ${PORTSNAP:="portsnap"}
: ${PORTSNAP_FETCH_ARGS:="fetch"}
: ${PORTSNAP_EXTRACT_ARGS:="extract"}
: ${PORTSNAP_UPDATE_ARGS:="update"}
: ${SVN:="svn"}
: ${SVN_CHECKOUT_ARGS:="checkout ${SVN_REPO_URL}"}
: ${SVN_PATCH_ARGS:="patch"}
: ${SVN_REVERT_ARGS:="revert -R"}
: ${SVN_STATUS_ARGS:="status"}
: ${SVN_UPDATE_ARGS:="update"}
: ${GIT:="git"}
: ${GIT_ADD_ARGS:="add -AN"}
: ${GIT_CLEAN_ARGS:="clean -fd -f"}
: ${GIT_CLONE_ARGS:="clone --depth 1 -b ${BRANCH} ${GIT_REPO_URL}"}
: ${GIT_GIT_PATCH_ARGS:="apply --whitespace=nowarn"}
: ${GIT_PATCH_ARGS:="apply -p0 --whitespace=nowarn"}
: ${GIT_RESET_ARGS:="reset --hard"}
: ${GIT_STATUS_ARGS:="status -s"}
: ${GIT_UPDATE_ARGS:="pull"}
: ${RM:="rm"}
: ${RM_ARGS:="-rf"}
: ${PORTLINT:="portlint"}
: ${PORTLINT_ARGS:="-A"}
: ${PORT:="port"}
: ${PORT_ARGS:="test"}
: ${PORTSDIR:="/usr/ports"}
: ${BULK_FILE:="build.ports.txt"}


: ${USE_POUDRIERE:="NO"}
: ${POUDRIERE_JAILS:=""}
: ${POUDRIERE_PORTSDIR:="/usr/local/poudriere/ports"}
: ${POUDRIERE_PORT:="default"}
: ${POUDRIERE:="poudriere"}
: ${POUDRIERE_ARGS:="bulk -t -C -p ${POUDRIERE_PORT}"}
: ${POUDRIERE_PORTS_ARGS:="ports -c -m ${METHOD} -p ${POUDRIERE_PORT}"}

# Set poudriere ports dir if being used #
if [ "${USE_POUDRIERE}" == "YES" ]; then
PORTSDIR="${POUDRIERE_PORTSDIR}/${POUDRIERE_PORT}"
fi

CURDIR="`pwd`"

# Check for commands #
${SVN} help >/dev/null 2>&1
if [ "$?" -ne "0" ]; then
	svnlite help >/dev/null 2>&1
	if [ "$?" -eq "0" ]; then
		SVN="svnlite"
	else
		SVN_CHECK="NO"
	fi
fi
${GIT} help >/dev/null 2>&1
if [ "$?" -ne "0" ]; then
	GIT_CHECK="NO"
fi
${PORTSNAP} >/dev/null 2>&1
if [ "$?" -ne "0" ]; then
	PORTSNAP_CHECK="NO"
fi

check_git() {
if [ "${GIT_CHECK}" == "NO" ]; then
echo "git not found. Try installing it, pkg install git" && exit 1
fi
}

check_svn() {
if [ "${SVN_CHECK}" == "NO" ]; then
echo "svn or svnlite not found. Try installing it, pkg install subversion" && exit 1
fi
}

check_empty_dir() {
	mkdir -p "$1"
	[ ! "`find \"$1\" -type d -empty -maxdepth 1`" ] && echo $1 is not empty && exit 1
}
### Create Repo ###
if [ "${CREATE_REPO}" -eq "1" ]; then
	if [ "${USE_POUDRIERE}" == "YES" ]; then
		${POUDRIERE} ${POUDRIERE_PORTS_ARGS}
	else
		case ${METHOD} in
			git*)
			check_git;
			check_empty_dir "${PORTSDIR}";
			${GIT} ${GIT_CLONE_ARGS} "${PORTSDIR}"
			if [ "$?" -ne "0" ]; then
			echo "git clone failed" && exit 1
			fi
			;;
			svn*)
			check_svn;
			check_empty_dir "${PORTSDIR}";
			${SVN} ${SVN_CHECKOUT_ARGS} "${PORTSDIR}"
			if [ "$?" -ne "0" ]; then
			echo "svn checkout failed" && exit 1
			fi
			;;
			portsnap)
			check_empty_dir "${PORTSDIR}";
			cd ${PORTSDIR} && PORTSDIR="`pwd`"
			if [ "${PORTSDIR}" != "/usr/ports" ]; then
				mkdir : ${PORTSNAP_WRKDIR:="${PORTSDIR}/.snap"}
				${PORTSNAP} -d "${PORTSNAP_WRKDIR}" -p "${PORTSDIR}" ${PORTSNAP_FETCH_ARGS} ${PORTSNAP_EXTRACT_ARGS}
			else
				${PORTSNAP} ${PORTSNAP_FETCH_ARGS} ${PORTSNAP_EXTRACT_ARGS}
			fi
			if [ "$?" -ne "0" ]; then
			echo "portsnap creation failed" && exit 1
			fi
			;;
		esac
	fi
fi
# Check PORTSDIR #
! [ -d "${PORTSDIR}" ] && echo "PORTSDIR not set or incorrect directory" && exit 1
cd ${PORTSDIR} && PORTSDIR="`pwd`"
: ${BACKUPDIR:="${PORTSDIR}/.bak"}

if [ "FreeBSD Ports Collection" != "`head -1 "${PORTSDIR}/README" | grep -o \"FreeBSD Ports Collection\"`" ]; then
	echo "PORTSDIR is set to an incorrect directory"
	exit 1
fi
# Check PORTSDIR is an svn or git tree #
cd ${PORTSDIR}
if [ "${SVN_CHECK}" != "NO" ]; then
	${SVN} info >/dev/null 2>&1
	if [ "$?" -eq "0" ]; then
		REPO_TYPE="svn"
		REPO="${SVN}"
		REPO_STATUS="${SVN_STATUS_ARGS}"
	fi
fi
if [ "${GIT_CHECK}" != "NO" ]; then
	${GIT} branch >/dev/null 2>&1
	if [ "$?" -eq "0" ]; then
		REPO_TYPE="git"
		REPO="${GIT}"
		REPO_STATUS="${GIT_STATUS_ARGS}"
	fi
fi
if [ -z "${REPO_TYPE}" ] && [ "${PORTSNAP_CHECK}" != "NO" ]; then
	if [ "${PORTSDIR}" != "/usr/ports" ]; then
		: ${PORTSNAP_WRKDIR:="${PORTSDIR}/.snap"}
		: ${PORTSNAP_ARGS:="-d ${PORTSNAP_WRKDIR} -p ${PORTSDIR}"}
	! [ -d "${PORTSNAP_WRKDIR}" ] && echo "Unsupported repo or portsnap wrkdir not found. Set PORTSNAP_WRKDIR if the latter" && exit 1
	else
		: ${PORTSNAP_WRKDIR:=""}
		: ${PORTSNAP_ARGS:=""}
	fi
	REPO_TYPE="portsnap"
fi

if [ "${REPO_BUILD_LIST}" -eq "1" ]; then
	case ${REPO_TYPE} in
	svn*);;
	git*);;
	*) echo "Port tree is not a svn or git repo, This is required with the -b option" && exit 1 ;;
	esac
fi

# Set patchfile path #
cd "${PORTSDIR}"
for file in "${@}"; do
	if [ -f "$file" ]; then
		PATCH_FILE="${PATCH_FILE} $file"
	elif [ -f "${CURDIR}/$file" ]; then
		PATCH_FILE="${PATCH_FILE} ${CURDIR}/$file"
	else
		echo "$file not found"
		exit 1
	fi
done

for file in ${PATCH_FILE}; do
	if [ "Index:" == "`head -4 \"$file\" | grep -m 1 -o \"^Index:\"`" ]; then
		SVN_PATCH_FILE="${SVN_PATCH_FILE} $file"
	elif [ "diff --git" == "`head -4 \"$file\" | grep -m 1 -o \"^diff \-\-git\"`" ]; then
		GIT_PATCH_FILE="${GIT_PATCH_FILE} $file"
	elif [ "diff" == "`head -4 \"$file\" | grep -m 1 -o \"^diff\"`" ]; then
		PATCH_PATCH_FILE="${PATCH_PATCH_FILE} $file"
	else
		echo "$file is not a recognized patch format"
		exit 1
	fi
done

# Check for valid jails #
if [ "${USE_POUDRIERE}" == "YES" ] && [ "${TEST_BUILD}" -eq "1" ]; then
	[ -z "${POUDRIERE_JAILS}" ] && echo "no jails selected use -j or export POUDRIERE_JAILS=\"jail1 jail2\"" && exit 1
	POUDRIERE_JAILS=`printf "%s\n" ${POUDRIERE_JAILS} | sort -u`
	for jail in ${POUDRIERE_JAILS}; do
	${POUDRIERE} jail -i -j $jail >/dev/null 2>&1
	[ $? -ne 0 ] && echo "No such jail $jail" && exit 1
	done
fi

git_revert() {
${GIT} ${GIT_RESET_ARGS}
${GIT} ${GIT_CLEAN_ARGS} -X
${GIT} ${GIT_CLEAN_ARGS}
}

portsnap_soft_revert() {
cd ${BACKUPDIR}
for dir in `find ./ -type d -maxdepth 1 | sed 's/\.\///' | grep '^[A-Z]'`; do
	${RM} ${RM_ARGS} "${PORTSDIR}/$dir"
	mv "${BACKUPDIR}/$dir" "${PORTSDIR}/$dir"
done
EMPTY_FOLDERS="`find ./ -type d -mindepth 2 -maxdepth 3 -empty | sed 's/^\.\///'`"
for dir in `find ./ -type d -mindepth 2 -maxdepth 2 | sed 's/^\.\///'`; do
	${RM} ${RM_ARGS} "${PORTSDIR}/$dir"
	[ -n "${EMPTY_FOLDERS}" ] && rmdir -p `echo "${EMPTY_FOLDERS}"` >/dev/null 2>&1
	[ -n "${EMPTY_FOLDERS}" ] && unset EMPTY_FOLDERS
	[ -d "${BACKUPDIR}/$dir" ] && mv "${BACKUPDIR}/$dir" "${PORTSDIR}/$dir"
done
for file in `find ./ -type f -maxdepth 2 | sed 's/^\.\///'`; do
	${RM} -f "${PORTSDIR}/$file"
	mv "${BACKUPDIR}/$file" "${PORTSDIR}/$file"
done
cd ${PORTSDIR}
${RM} -r "${BACKUPDIR}"
${RM} `find ./ -maxdepth 2 -name "*.[ro][er][ji]*"` >/dev/null 2>&1
}

svn_hard_revert() {
cd ${PORTSDIR}
for file in `${SVN} status | awk '{ print $(NF) }'`; do
	${RM} ${RM_ARGS} "${PORTSDIR}/$file"
done
${SVN} ${SVN_REVERT_ARGS} ${PORTSDIR}
${RM} `find ./ -maxdepth 1 -name "*.[ro][er][ji]*"` >/dev/null 2>&1
}

### Update Repo ###
if [ "${UPDATE_REPO}" -eq "1" ]; then
cd ${PORTSDIR}
	case ${REPO_TYPE} in
		svn)
			svn_hard_revert
			${SVN} ${SVN_UPDATE_ARGS}
		;;
		git)
			git_revert
			${GIT} ${GIT_UPDATE_ARGS}
		;;
		portsnap)
			[ -d "${BACKUPDIR}" ] && portsnap_soft_revert
			${PORTSNAP} ${PORTSNAP_ARGS} ${PORTSNAP_FETCH_ARGS} ${PORTSNAP_UPDATE_ARGS}
	esac
fi

filelist() {
[ -n "${SVN_PATCH_FILE}" ] && PATCH_FILES_LIST="`cat ${SVN_PATCH_FILE} | grep '^Index:[ ].*' | awk '{ print $(NF) }'`"
[ -n "${GIT_PATCH_FILE}" ] && PATCH_FILES_LIST="${PATCH_FILES_LIST}
"`cat ${GIT_PATCH_FILE} | grep "^diff \-\-git" | awk '{ print $(NF) }' | sed 's/^b\///'`
[ -n "${PATCH_PATCH_FILE}" ] && PATCH_FILES_LIST="${PATCH_FILES_LIST}
"`cat ${PATCH_PATCH_FILE} | grep "^diff" | awk '{ print $(NF) }'`
}
folderlist() {
[ -z "${PATCH_FILES_LIST}" ] && filelist
[ -n "${PATCH_FILES_LIST}" ] && PATCH_FOLDER_LIST="`echo "${PATCH_FILES_LIST}" | grep -o '^[^/]*\/[^/]*\/' | sed 's/\/$//'`"
[ -n "${PATCH_FOLDER_LIST}" ] && PATCH_FOLDER_LIST="${PATCH_FOLDER_LIST}
"`echo "${PATCH_FILES_LIST}" | grep -o '^[^/]*\/[^/]*\/[^/]*\/' | sed 's/\/$//'`
[ -n "${PATCH_FOLDER_LIST}" ] && PATCH_FOLDER_LIST="`echo "${PATCH_FOLDER_LIST}" | sort -u`"
}

### Patch Tree ###
if [ "${DO_PATCH}" -eq "1" ] || [ "${ALL}" -eq "1" ]; then
	[ -z "${PATCH_FOLDER_LIST}" ] && folderlist
	case ${REPO_TYPE} in
	portsnap*)	mkdir -p ${BACKUPDIR} && cd ${BACKUPDIR}
			mkdir -p `echo "${PATCH_FILES_LIST}" | sed 's/^[A-Z].*//' | grep -o '^[^/]*\/[^/]*\/' | sed 's/\/$// ; s/[^/]*$//' | sort -u`
			cd ${PORTSDIR}
			for dir in `find ./ -type d -maxdepth 1 | sed 's/^\.\///' | grep '^[A-Z]'`; do
				! [ -d "${BACKUPDIR}/$dir" ] && cp -Ra "${PORTSDIR}/$dir" "${BACKUPDIR}/$dir"
			done
			for file in `find ./ -type f -maxdepth 2 | sed 's/^\.\///'`; do
				! [ -f "${BACKUPDIR}/$file" ] && cp -a "${PORTSDIR}/$file" "${BACKUPDIR}/$file" >/dev/null 2>&1
			done
			for dir in `echo "${PATCH_FOLDER_LIST}"`; do
				! [ -d "${PORTSDIR}/$dir" ] && mkdir -p "${PORTSDIR}/$dir"
			done
			for dir in `echo "${PATCH_FILES_LIST}" | grep -o '^[^/]*\/[^/]*\/' | sed 's/\/$//' | sort -u`; do
				! [ -d "${BACKUPDIR}/$dir" ] && cp -Ra "${PORTSDIR}/$dir" "${BACKUPDIR}/$dir"
			done ;;
	git*)		for dir in `echo "${PATCH_FOLDER_LIST}"`; do
				! [ -d "${PORTSDIR}/$dir" ] && mkdir -p "${PORTSDIR}/$dir"
			done ;;
	svn*)	;;
	esac
	case ${REPO_TYPE} in
	svn*)	for file in ${SVN_PATCH_FILE}; do
		PATCH_OUTPUT="${PATCH_OUTPUT}
"`${SVN} ${SVN_PATCH_ARGS} "$file" "${PORTSDIR}"`
		done
		for file in ${GIT_PATCH_FILE}; do
		PATCH_OUTPUT="${PATCH_OUTPUT}
"`${SVN} ${SVN_PATCH_ARGS} "$file" "${PORTSDIR}"`
		done
		for file in ${PATCH_PATCH_FILE}; do
		PATCH_OUTPUT="${PATCH_OUTPUT}
"`${SVN} ${SVN_PATCH_ARGS} "$file" "${PORTSDIR}"`
		done 
		if [ "`echo "${PATCH_OUTPUT}" | grep -m 1 -o reject`" == "reject" ]; then
			echo "${PATCH_OUTPUT}"
			echo "Patch Failed"
			exit 1
		fi ;;
	git*)	cd ${PORTSDIR}
		for file in ${SVN_PATCH_FILE}; do
		PATCH_OUTPUT="${PATCH_OUTPUT}
"`${GIT} ${GIT_PATCH_ARGS} "$file" 2>&1`
		done
		for file in ${GIT_PATCH_FILE}; do
		PATCH_OUTPUT="${PATCH_OUTPUT}
"`${GIT} ${GIT_GIT_PATCH_ARGS} "$file" 2>&1`
		done
		for file in ${PATCH_PATCH_FILE}; do
		PATCH_OUTPUT="${PATCH_OUTPUT}
"`${GIT} ${GIT_PATCH_ARGS} "$file" 2>&1`
		done
		if [ "`echo "${PATCH_OUTPUT}" | grep -m 1 -o error`" == "error" ]; then
			echo "${PATCH_OUTPUT}"
			echo "Patch Failed"
			exit 1
		fi
		${GIT} ${GIT_ADD_ARGS} ${PATCH_FOLDER_LIST}
		${RM} `find ${PATCH_FOLDER_LIST} -maxdepth 1 -empty`
;;

	*)	for file in ${SVN_PATCH_FILE}; do 
		PATCH_OUTPUT="${PATCH_OUTPUT}
"`${PATCH} ${PATCH_SVN_ARGS} -d "${PORTSDIR}" -i "$file"`
		done
		for file in ${GIT_PATCH_FILE}; do
		PATCH_OUTPUT="${PATCH_OUTPUT}
"`${PATCH} ${PATCH_GIT_ARGS} -d "${PORTSDIR}" -i "$file"`
		done
		for file in ${PATCH_PATCH_FILE}; do
		PATCH_OUTPUT="${PATCH_OUTPUT}
"`${PATCH} ${PATCH_PATCH_ARGS} -d "${PORTSDIR}" -i "$file"`
		done
		if [ "`echo "${PATCH_OUTPUT}" | grep -m 1 -o rejects`" == "rejects" ]; then
			echo "${PATCH_OUTPUT}"
			echo "Patch Failed"
			exit 1
		fi
		cd ${PORTSDIR}
		${RM} `find ${PATCH_FOLDER_LIST} -maxdepth 1 -name "*.orig"` ;;
	esac
fi

# Generate a list of ports for poudriere to build #
buildlist() {

if [ "${REPO_BUILD_LIST}" -eq "1" ]; then
cd ${PORTSDIR}
BUILD_LIST="`${REPO} ${REPO_STATUS} | awk '{ print $(NF) }' | sed 's/^[A-Z].*//' | grep -o '^[^/]*\/[^/]*\/' | sed 's/\/$//' | sort -u`"
else
[ -z "${PATCH_FILES_LIST}" ] && filelist
BUILD_LIST="`echo "${PATCH_FILES_LIST}" | sed 's/^[A-Z].*//' | grep -o '^[^/]*\/[^/]*\/' | sed 's/\/$//' | sort -u`"
fi
}

### Bulk File ###
if [ "$POUDRIERE_BULK" -eq "1" ]; then
	[ -z "${BUILD_LIST}" ] && buildlist
	cd "${CURDIR}"
	echo "${BUILD_LIST}" >"${POUDRIERE_BULK_FILE}"
elif [ "${ALL}" -eq "1" ]; then
	[ -z "${BUILD_LIST}" ] && buildlist
	cd "${CURDIR}"
	echo "${BUILD_LIST}" >"${BULK_FILE}"
fi

### Portlint ###
if [ "${TEST_PORTLINT}" -eq "1" ] || [ "${ALL}" -eq "1" ]; then
	[ -z "${BUILD_LIST}" ] && buildlist
	for port in ${BUILD_LIST}; do
		cd "${PORTSDIR}/$port"
		echo "$port"
		${PORTLINT} ${PORTLINT_ARGS}
	done
fi


### Port test and Poudriere testing ###
if [ "${TEST_BUILD}" -eq "1" ] && [ "${USE_POUDRIERE}" != "YES" ]; then
	${RM} ${RM_ARGS} "`find ${PORTSDIR} -type d -name "work" -maxdepth 3`"
	[ -z "${BUILD_LIST}" ] && buildlist
	for port in ${BUILD_LIST}; do
		cd "${PORTSDIR}/$port"
		make depends BATCH=yes
		${PORT} ${PORT_ARGS}
	done
elif [ "${TEST_BUILD}" -eq "1" ] && [ "${USE_POUDRIERE}" == "YES" ]; then
	[ -z "${BUILD_LIST}" ] && buildlist
	TMUX_OPEN=1
	TMUX_SESSION="portest-`openssl rand -hex 64`"
	for jail in ${POUDRIERE_JAILS}; do
		[ -n "${TMUX_OPEN}" ] && tmux new-session -ds "${TMUX_SESSION}" ${POUDRIERE} ${POUDRIERE_ARGS} -j $jail ${BUILD_LIST}
		! [ -n "${TMUX_OPEN}" ] && tmux split-window -dt "${TMUX_SESSION}" ${POUDRIERE} ${POUDRIERE_ARGS} -j $jail ${BUILD_LIST}
		[ -n "${TMUX_OPEN}" ] && unset TMUX_OPEN
	done
	tmux select-layout -t "${TMUX_SESSION}" tiled
	tmux attach-session -t "${TMUX_SESSION}" >/dev/null 2>&1
	if [ "$?" -ne 0 ]; then
		tmux switch -t "${TMUX_SESSION}"
	fi
fi

### Revert Patch ###
cd ${PORTSDIR}
case ${REPO_TYPE} in
	svn)
if [ "${REVERT_SOFT}" -eq "1" ] && [ "${REVERT_HARD}" -ne "1" ]; then
	[ -z "${BUILD_LIST}" ] && buildlist
# Wierd cases where svn won't see short filenames in list.    #
# This seems to be an svn bug, this list helps in those cases #
	PATCH_FILES_FILTERED="`echo "${PATCH_FILES_LIST}" | grep -v '^[^/]*\/[^/]*\/[^/]*'`"
	for file in ${BUILD_LIST}; do
		${RM} ${RM_ARGS} "${PORTSDIR}/$file"
	done
	for file in ${PATCH_FILES_LIST}; do
		${RM} ${RM_ARGS} "${PORTSDIR}/$file"
	done
	[ -n "${BUILD_LIST}" ] && ${SVN} ${SVN_REVERT_ARGS} ${BUILD_LIST}
	[ -n "${PATCH_FILES_LIST}" ] && ${SVN} ${SVN_REVERT_ARGS} ${PATCH_FILES_LIST}
	[ -n "${PATCH_FILES_FILTERED}" ] && ${SVN} ${SVN_REVERT_ARGS} ${PATCH_FILES_FILTERED}
	${RM} `find ./ -maxdepth 1 -name "*.[ro][er][ji]*"` >/dev/null 2>&1
elif [ "${REVERT_HARD}"  -eq "1" ]; then
	svn_hard_revert
fi
	;;
	git)
if [ "${REVERT_SOFT}" -eq "1" ] || [ "${REVERT_HARD}" -eq "1" ]; then
	git_revert
fi
	;;
	portsnap)
if [ "${REVERT_SOFT}" -eq "1" ] && [ "${REVERT_HARD}" -ne "1" ]; then
	! [ -d "${BACKUPDIR}" ] && echo "Nothing to revert, try the -R option?" && exit 1
	portsnap_soft_revert
elif [ "${REVERT_HARD}"  -eq "1" ]; then
	${PORTSNAP} ${PORTSNAP_ARGS} ${PORTSNAP_EXTRACT_ARGS}
	cd ${PORTSDIR}
	${RM} ${RM_ARGS} "${BACKUPDIR}"
	${RM} `find ./ -maxdepth 1 -name "*.[ro][er][ji]*"` >/dev/null 2>&1
fi
	;;
esac
